### PR TITLE
Log failed flag attempts

### LINKED ISSUE #31: Log failed flag attempts

### PR DESCRIPTION
**Pull request by gregoryzli**
Closes #31

Adds logging for failed flag attempts to improve visibility and debugging.

### CODE REVIEW

File: migrations/1768183790000_add-attempt-createdat.js [hunk 1]
```diff
@@ -0,0 +1,9 @@
+exports.up = function (pgm) {
```
Comment (Aplet123) [inline migrations/1768183790000_add-attempt-createdat.js]: Not a big deal but can this migration be merged into the previous one so we can reduce migration count?

**Review by Aplet123 — CHANGES_REQUESTED** [review]

**Review by Aplet123 — APPROVED** [review]
LGTM, thanks!
